const fs = require('fs')
let code = fs.readFileSync('src/components/quick-sale/QuickSaleForm.tsx', 'utf8')
code = code.replace(/const \[isAddingVehicle, setIsAddingVehicle\] = useState\(false\)/, 'const [isAddingVehicle, setIsAddingVehicle] = useState(false)\n  const [isSavingVehicle, setIsSavingVehicle] = useState(false)')
fs.writeFileSync('src/components/quick-sale/QuickSaleForm.tsx', code)
console.log("Fixed QS state")
